### ISSUE TITLE
Items error

### ISSUE THREAD

**Issue by aman220320072007** [eendroroy/alacritty-theme#29]
While changing themes this error comes up 
/usr/local/lib/node_modules/alacritty-themes/index.js:27
  const colors = doc.contents.items.filter((i) => i.key.value === "colors")[0];
                              ^

TypeError: Cannot read property 'items' of null
    at updateTheme (/usr/local/lib/node_modules/alacritty-themes/index.js:27:31)
    at /usr/local/lib/node_modules/alacritty-themes/index.js:83:7
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

Pop os 20.10 a debinan linux distro

![Screenshot from 2021-01-27 22-07-10](https://user-images.githubusercontent.com/75264859/106022649-15400e80-60ec-11eb-9b68-bdd730ae6df8.png)

**Comment by aman220320072007** [comment]
Please fix this asap

**Comment by eendroroy** [comment]
This is not the repo you are using.
