### ISSUE TITLE
can`t select a theme

### ISSUE THREAD

**Issue by VaskMykola** [eendroroy/alacritty-theme#33]
After installation I used this [tutorial](https://www.funkyspacemonkey.com/how-to-easily-apply-and-change-alacritty-themes) to install alacritty-theme, after that I made alacritty.yml (blank file) in ~/.config/alacritty/. After run, I wrote theme but every one of them gives me this error.

**Comment by VaskMykola** [comment]
? Select a theme › dr
❯   Dracula(node:120792) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'items' of null
    at updateTheme (/usr/local/lib/node_modules/alacritty-themes/index.js:84:31)
    at readFile.then (/usr/local/lib/node_modules/alacritty-themes/index.js:117:12)
(node:120792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with

**Comment by eendroroy** [comment]
The tutorial you are following seems to be using different repo. It is not applicable for this repo.
