### ISSUE TITLE
Color Scheme Request: Moonlight II

### ISSUE THREAD

**Issue by AdsonCicilioti** [eendroroy/alacritty-theme#36]
**Request new color: Moonligth II from [VSCode Color theme](https://github.com/atomiks/moonlight-vscode-theme)**

One Beautiful color scheme.

![image](https://user-images.githubusercontent.com/6278398/140259706-5aa53308-74cf-4f66-8717-05a870991cfc.png)

Thx!

**Comment by eendroroy** [comment]
https://github.com/eendroroy/alacritty-theme/blob/master/themes/moonlight_ii_vscode.yaml
