### ISSUE TITLE
Move alacritty-theme upstream

### ISSUE THREAD

**Issue by chrisduerr** [eendroroy/alacritty-theme#58]
Alacritty's Wiki was recently made private due to repeated griefing, which in turn means that people are not able to add new colorschemes to the wiki anymore.

The obvious solution to that is to create a separate theme repository where people can add colorschemes through PRs rather than just throwing them in the wiki, which is what this repository does.

You seem to have done a good job maintaining these themes, providing helpful screenshots for each one. So I wanted to reach out and ask if you're interested in upstreaming this repository to the Alacritty organization before just forking it myself.

There might be some changes this repository could benefit from, but I don't think it would need major modifications.

**Comment by ngortheone** [comment]
As a user of both `alacritty` and `alacritty-theme` I am very excited to see this. I hope @eendroroy will agree to this.

**Comment by eendroroy** [comment]
@chrisduerr 
Glad to know that you liked the repo.

I haven't done this before in Github. If you can let me know the process and future maintenance procedure, it would be helpful for me.

**Comment by chrisduerr** [comment]
In https://github.com/eendroroy/alacritty-theme/settings at the bottom there should be an option to "transfer ownership" where you can transfer it to the Alacritty org. That would likely be the best option since it will redirect people from the old repo to the new location.

But you can also keep this repo if you prefer to still have it around for yourself and I'll just copy it to the org manually. Would probably just put a notice in the description somewhere about the new "main" repo.

As far as maintenance is concerned, I'd just add you as an outside collaborator for that repository. Which should mean you still have all the permissions and stuff for the new repo.

**Comment by eendroroy** [comment]
Thanks for explaining.

I would like to keep the repo. I can make it a public archive and point to the org repo.

**Comment by chrisduerr** [comment]
I've created https://github.com/alacritty/alacritty-theme and added you as a maintainer. Let me know if there are any issues.

**Comment by eendroroy** [comment]
I have put a notice at the top of the README.
Closing the issue now and archiving the repository.
