### ISSUE TITLE
Colors aren't shown as screenshots depicted

### ISSUE THREAD

**Issue by nikolaof** [eendroroy/alacritty-theme#7]
Hi. I'm using the solarized dark theme but I noticed that colors are not the same as the picture you have. For example, when typing ls -la command the write permission is not red or the timestamps are not blue. Instead all letters have the same foreground color. Is this a misconfiguration of the alacritty or something else? Thanks.

**Comment by eendroroy** [comment]
It's not a configuration issue.
The colors are different because  I use `exa` aliased as `ls`.

Thanks for pointing out the issue. I will update the images.

**Comment by eendroroy** [comment]
Images updated.

It seems github now takes some time to reflect changes in images. The old images might still show in readme for some time.
